import java.util.*;
import java.io.*;

public class Main {	
	public static void main(String[] args) throws IOException, Exception {
		 try {
			 //예외가 발생할 수 있는 문장들을 넣느다
		 }catch(Exception e1){
			 //Exception e1이 발생했을경우 이를 처리하기위한 문장
		 }catch(Exception e2){
			 //Exception e2이 발생했을경우 이를 처리하기위한 문장
		 }catch(Exception en){
			 //Exception en이 발생했을경우 이를 처리하기위한 문장
		 }

	}
	
}
//try사용후 catch로 여러 예외를 catch할수 있지만 위에서 한번 잡힌 예외는 잡을 수 없다
